### PR TITLE
Zoom slider

### LINKED ISSUE #42: Zooming
It would be cool to have a zooming slider on pages like mac os

image

### PR DESCRIPTION
**Pull request by hola-soy-milk**
Closes #42 
zoomed out
zoomed in

### CODE REVIEW

**Comment by SaraVieira** [comment]
uhhh, niiice!

I do think the magnifying UI should be at the bottom like on the mac no?

**Comment by hola-soy-milk** [comment]
Ahh! Good point, that does make it less cluttered!

**Comment by hola-soy-milk** [comment]
Slider at the bottom right

I agree this is much better, ty!

**Review by SaraVieira — APPROVED** [review]
This is awesome!!! Thank you!

**Pull request merged**
