### PR TITLE
Add disk space & card icons

### PR DESCRIPTION
**Pull request by SaraVieira**
CleanShot 2023-12-16 at 14 31 37@2x
CleanShot 2023-12-16 at 14 31 51@2x

### CODE REVIEW

**Review by hola-soy-milk — APPROVED** [review]
YESS 🔥

**Comment by hola-soy-milk** [comment]
Oops not done yet my bad

**Review by hola-soy-milk — APPROVED** [review]
Amazing stuff!!! So excited for this

**Comment by hola-soy-milk** [comment]
Hm, there seems to be some lint checks and this is still marked as WIP?

**Comment by SaraVieira** [comment]
Dang it, will fix them when I back at the laptop

**Comment by hola-soy-milk** [comment]
Woohoo!! Nice one

**Pull request merged**
